export const ESTADO_OT = {
  POR_REALIZAR: "POR_REALIZAR",
  EN_ESPERA: "EN_ESPERA",
  EN_CURSO: "EN_CURSO",
  LISTO_PARA_ENTREGAR: "LISTO_PARA_ENTREGAR",
  ENTREGADO: "ENTREGADO",
  ANULADA: "ANULADA",
} as const

export type EstadoOt = (typeof ESTADO_OT)[keyof typeof ESTADO_OT]

export const NOMBRES_ESTADO_OT: Record<EstadoOt, string> = {
  [ESTADO_OT.POR_REALIZAR]: "Por realizar",
  [ESTADO_OT.EN_ESPERA]: "En espera",
  [ESTADO_OT.EN_CURSO]: "En curso",
  [ESTADO_OT.LISTO_PARA_ENTREGAR]: "Listo para entregar",
  [ESTADO_OT.ENTREGADO]: "Entregado",
  [ESTADO_OT.ANULADA]: "Anulada",
}

export const TRANSICIONES_OT: Record<EstadoOt, EstadoOt[]> = {
  [ESTADO_OT.POR_REALIZAR]: [ESTADO_OT.EN_CURSO, ESTADO_OT.EN_ESPERA],
  [ESTADO_OT.EN_CURSO]: [ESTADO_OT.LISTO_PARA_ENTREGAR, ESTADO_OT.EN_ESPERA],
  [ESTADO_OT.EN_ESPERA]: [ESTADO_OT.EN_CURSO, ESTADO_OT.LISTO_PARA_ENTREGAR],
  [ESTADO_OT.LISTO_PARA_ENTREGAR]: [ESTADO_OT.ENTREGADO, ESTADO_OT.EN_CURSO],
  [ESTADO_OT.ENTREGADO]: [],
  [ESTADO_OT.ANULADA]: [],
}

export const ACTIVE_WORK_ORDER_STATUSES: EstadoOt[] = [
  ESTADO_OT.POR_REALIZAR,
  ESTADO_OT.EN_CURSO,
  ESTADO_OT.EN_ESPERA,
  ESTADO_OT.LISTO_PARA_ENTREGAR,
]

export const ESTADOS_OT_FINALIZADOS: EstadoOt[] = [
  ESTADO_OT.LISTO_PARA_ENTREGAR,
  ESTADO_OT.ENTREGADO,
]

export const ESTADOS_OT_CERRADOS: EstadoOt[] = [
  ESTADO_OT.ENTREGADO,
  ESTADO_OT.ANULADA,
]

export function getNombreEstadoOt(estado: string, nombre?: string | null) {
  return nombre || NOMBRES_ESTADO_OT[estado as EstadoOt] || estado
}
