name: Playwright Tests
on:
  push:
    branches: [ main, master, rama-tests ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      env:
        E2E_BASE_URL: https://urban-cycling-dashboard-mxtixs-projects.vercel.app
        E2E_EMAIL: qa.admin.db@urbancycling.cl
        E2E_PASSWORD: ${{ secrets.E2E_QA_PASSWORD }}
      run: npx playwright test
    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
